Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Medical.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Admin/Dashboard
        public ActionResult Index()
        {
            return View("Dashboard");
        }
    }
}

Areas/Department/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Medical.BAL;
using Newtonsoft.Json;
using Medical.Framework;
using Medical.Models;
using System.Data;

namespace Medical.Areas.Department.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Department/Dashboard
        #region Global
        DashboardBAL objBAL;
        #endregion
        public ActionResult Dashboard()
        {
            return View();
        }
        public string BindCounts()
        {
            objBAL = new DashboardBAL();
            DataTable dt = objBAL.GetDeptUserDashboadCounts(Session.GetDataFromSession<UserModel>("User"));
            return JsonConvert.SerializeObject(objBAL.GetDeptUserDashboadCounts(Session.GetDataFromSession<UserModel>("User")));
        }
        public ActionResult DepartmentAdmin()
        {
            return View();
        }
    }
}

Areas/User/Controllers/ApplicationController.cs
using Medical.BAL;
using Medical.Framework;
using Medical.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Medical.Areas.User.Controllers
{
  
    public class ApplicationController : Controller
    {
        LicenseBAL licenseBAL;
        PCPNDTBAL pcpndtBAL;
        ApplicationBAL applicationBAL;
        // GET: User/Application
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult GetAcknowledge(int applicationId)
        {
            applicationBAL = new ApplicationBAL();
            AcknowledgeModel model = applicationBAL.GetAcknowledgeDetails(applicationId);            
            return PartialView("_Acknowledgement", model);
        }
        public void ClearData()
        {
            Session["ApplicationId"] = null;
            Session["PCPNDTTransactionId"] = null;
            Session["EquipmentsList"] = null;
            Session["EmployeeList"] = null;
            Session["APMCETransactionId"] = null;
            Session["AddressProofPath"] = null;
            Session["BuildingLayoutPath"] = null;
        }

        public JsonResult DeleteStudyCertificate(int id)
        {
            var studyCertificates = Session.GetDataFromSession<List<DocumentUploadModel>>("StudyCertificates");
            studyCertificates.Where(item => item.Id == id).First().IsDeleted = true;
            studyCertificates.Where(item => item.Id == id).First().
                LastModifiedUserId = Session.GetDataFromSession<UserModel>("User").Id;
            Session.SetDataToSession<List<DocumentUploadModel>>("StudyCertificates", studyCertificates);
            
            return Json(studyCertificates.Where(item => item.IsDeleted == false).ToList());
        }
    }
}

Areas/User/Controllers/DashboardController.cs
using Medical.BAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Medical.Framework;
using Medical.Models;
using System.Data;
using Newtonsoft.Json;

namespace Medical.Areas.User.Controllers
{
    
    public class DashboardController : Controller
    {
        DashboardBAL dashboardBAL;

        // GET: User/Dashboard
        public ActionResult Index()
        {
            return View("Dashboard");
        }

        public string GetUserDashboard()
        {
            dashboardBAL = new DashboardBAL();
            int _userId = Session.GetDataFromSession<UserModel>("User").Id;
            DataSet ds = dashboardBAL.GetUserDashboard(_userId);
            return JsonConvert.SerializeObject(ds);
        }

        public ViewResult Drafts()
        {
            return View();
        }

        public string GetDraftApplications()
        {
            dashboardBAL = new DashboardBAL();
            int _userId = Session.GetDataFromSession<UserModel>("User").Id;
            DataTable dt = dashboardBAL.GetDraftApplications(_userId);
            return JsonConvert.SerializeObject(dt);
        }

        public ViewResult Submitted()
        {
            return View();
        }

        public string GetSubmittedApplications()
        {
            dashboardBAL = new DashboardBAL();
            int _userId = Session.GetDataFromSession<UserModel>("User").Id;
            DataTable dt = dashboardBAL.GetSubmittedApplications(_userId);
            return JsonConvert.SerializeObject(dt);
        }

        public ViewResult Licenses()
        {
            return View();
        }

        public string GetLicenses()
        {
            dashboardBAL = new DashboardBAL();
            int _userId = Session.GetDataFromSession<UserModel>("User").Id;
            DataTable dt = dashboardBAL.GetLicenses(_userId);
            return JsonConvert.SerializeObject(dt);
        }
    }
}

Areas/User/Controllers/LicenseController.cs
using Medical.BAL;
using Medical.Framework;
using Medical.Models;
//using RazorPDF;
//using Rotativa;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Medical.Areas.User.Controllers
{

    public class LicenseController : Controller
    {
        LicenseBAL objBAL;
        ApplicationBAL applicationBAL;
        PCPNDTBAL pcpndtBAL;
        APMCEBAL apmceBAL;
        // GET: User/License
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult Questionnaire()
        {
            return View(new LicenseQuestionnaireModel());
        }

        [HttpPost]
        public ActionResult Questionnaire(LicenseQuestionnaireModel model)
        {
            ClearData();

            objBAL = new LicenseBAL();
            ViewBag.DistrictList = objBAL.GetDistrictList();

            if (model.HasAppliedforAPMCE)
            {
                ViewBag.OfferedServices = objBAL.GetOfferedServices();
            }

            if (model.HasAppliedforPCPNDT)
            {
                List<OwnershipTypeModel> ownershipTypeList = new List<OwnershipTypeModel>();
                List<InstitutionTypeModel> institutionTypeList = new List<InstitutionTypeModel>();
                objBAL.GetOwnershipMasterData(ref ownershipTypeList, ref institutionTypeList);
                ViewBag.OwnershipTypeList = ownershipTypeList;
                ViewBag.InstitutionTypeList = institutionTypeList;
                ViewBag.FacilityMaster = objBAL.GetFacilityList();
                TempData["DoctorSpecialityList"] = objBAL.GetDoctorSpecialityList();
            }
            return View("ApplicationForm", model);
        }


        #region Applications
        public ViewResult ApplicationForm()
        {
            ClearData();

            objBAL = new LicenseBAL();
            ViewBag.DistrictList = objBAL.GetDistrictList();
            LicenseQuestionnaireModel model = new LicenseQuestionnaireModel();

            
            if (model.HasAppliedforPCPNDT)
            {
                List<OwnershipTypeModel> ownershipTypeList = new List<OwnershipTypeModel>();
                List<InstitutionTypeModel> institutionTypeList = new List<InstitutionTypeModel>();
                objBAL.GetOwnershipMasterData(ref ownershipTypeList, ref institutionTypeList);
                ViewBag.OwnershipTypeList = ownershipTypeList;
                ViewBag.InstitutionTypeList = institutionTypeList;
                ViewBag.FacilityMaster = objBAL.GetFacilityList();
                ViewBag.OfferedServices = objBAL.GetOfferedServices();
                TempData["DoctorSpecialityList"] = objBAL.GetDoctorSpecialityList();
            }
            return View(model);
        }
        public ViewResult ApplicationView(int id)
        {
            objBAL = new LicenseBAL();
            ApplicationModel model = objBAL.GetApplication(id);
            return View(model);
        }
        public ViewResult Edit(int id)
        {
            objBAL = new LicenseBAL();
            ViewBag.DistrictList = objBAL.GetDistrictList();

            LicenseQuestionnaireModel model = new LicenseQuestionnaireModel();

            model.ApplicationModel = objBAL.GetApplication(id);
            if (model.ApplicationModel.APMCEModel != null)
                model.HasAppliedforAPMCE = true;
            if (model.ApplicationModel.PCPNDTModel != null)
                model.HasAppliedforPCPNDT = true;

            Session["ApplicationId"] = id;
            if (model.ApplicationModel.APMCEModel != null)
            {
                ViewBag.OfferedServices = objBAL.GetOfferedServices();
                Session["APMCETransactionId"] = model.ApplicationModel.APMCEModel.TransactionId;

                // Set file paths
                if(model.ApplicationModel.APMCEModel.Accommadation != null && 
                    model.ApplicationModel.APMCEModel.Accommadation.UploadedFilePath != null)
                    Session["AccommodationFilePath"] = model.ApplicationModel.APMCEModel.Accommadation.UploadedFilePath;
            }
                
            if (model.ApplicationModel.PCPNDTModel != null)
            {
                List<OwnershipTypeModel> ownershipTypeList = new List<OwnershipTypeModel>();
                List<InstitutionTypeModel> institutionTypeList = new List<InstitutionTypeModel>();
                objBAL.GetOwnershipMasterData(ref ownershipTypeList, ref institutionTypeList);
                ViewBag.OwnershipTypeList = ownershipTypeList;
                ViewBag.InstitutionTypeList = institutionTypeList;
                ViewBag.FacilityMaster = objBAL.GetFacilityList();
                TempData["DoctorSpecialityList"] = objBAL.GetDoctorSpecialityList();

                Session["PCPNDTTransactionId"] = model.ApplicationModel.PCPNDTModel.TransactionId;
                Session["EquipmentsList"] = model.ApplicationModel.PCPNDTModel.EquipmentList;
                Session["EmployeeList"] = model.ApplicationModel.PCPNDTModel.EmployeeList;

                // Set file paths
                Session["AddressProofPath"] = model.ApplicationModel.PCPNDTModel.FacilityModel.AddressProofPath;
                Session["BuildingLayoutPath"] = model.ApplicationModel.PCPNDTModel.FacilityModel.BuildingLayoutPath;
                Session["AffidavitDocPath"] = model.ApplicationModel.PCPNDTModel.InstitutionModel.AffidavitDocPath;
                Session["ArticleFilePath"] = model.ApplicationModel.PCPNDTModel.InstitutionModel.ArticleDocPath;
                Session["StudyCertificates"] = model.ApplicationModel.PCPNDTModel.InstitutionModel.StudyCertificateDocPaths;                
            }

            return View("ApplicationForm", model);
        }
        public ActionResult Applications()
        {
            objBAL = new LicenseBAL();
            int _userId = Session.GetDataFromSession<UserModel>("User").Id;
            List<ApplicationModel> objList = objBAL.GetApplicationList(_userId);
            return View(objList);
        }
        public PartialViewResult PreviewApplication()
        {
            int _applicationId = Session.GetDataFromSession<int>("ApplicationId");
            objBAL = new LicenseBAL();
            ApplicationModel application = objBAL.GetApplication(_applicationId);
            return PartialView("_ApplicationPreview", application);
        }
        public JsonResult SubmitApplication()
        {
            int _applicationId = Session.GetDataFromSession<int>("ApplicationId");
            string _applicationNumber = string.Empty;

            applicationBAL = new ApplicationBAL();
            int result = applicationBAL.SubmitApplication(_applicationId, ref _applicationNumber);
            NotificationModel notificationModel = new NotificationModel();
            if (result > 0)
            {
                notificationModel.Title = "Success";
                notificationModel.NotificationType = NotificationType.Success;
                notificationModel.NotificationMessage = "Application has been sumbitted successfully"
                    + "<br>Your application number is <b>" + _applicationNumber + "</b>"
                    + "<br>Please note this for your future reference";
                notificationModel.ShowActionButton = true;
                notificationModel.ActionButtonClassType = PopupButtonClass.Success;
                notificationModel.ActionButtonText = "View Applications";
                notificationModel.ActionName = "Submitted";
                notificationModel.ControllerName = "Dashboard";
                notificationModel.AreaName = "User";
                ClearData();
            }
            else
            {
                notificationModel.Title = "Error";
                notificationModel.NotificationType = NotificationType.Danger;
                notificationModel.NotificationMessage = "Oops! something went wrong. Please contact helpdesk";
                notificationModel.ShowNonActionButton = true;
                notificationModel.NonActionButtonClassType = PopupButtonClass.Danger;
                notificationModel.NonActionButtonText = "Okay";
            }
            return Json(notificationModel);
        }
        public ActionResult Print()
        {


            objBAL = new LicenseBAL();
            ViewBag.DistrictList = objBAL.GetDistrictList();

            LicenseQuestionnaireModel model = new LicenseQuestionnaireModel();
            model.HasAppliedforPCPNDT = true;

            if (model.HasAppliedforPCPNDT)
            {
                List<OwnershipTypeModel> ownershipTypeList = new List<OwnershipTypeModel>();
                List<InstitutionTypeModel> institutionTypeList = new List<InstitutionTypeModel>();
                objBAL.GetOwnershipMasterData(ref ownershipTypeList, ref institutionTypeList);
                ViewBag.OwnershipTypeList = ownershipTypeList;
                ViewBag.InstitutionTypeList = institutionTypeList;
            }

            model.ApplicationModel = objBAL.GetApplication(175);
            //return new RazorPDF.PdfResult(model, "_ApplicationPreview");

            //var pdf = new PdfResult(model, "_ApplicationPreview");
            //pdf.ViewBag.Title = "Report Title";
            //return pdf;
            return null;
        }
        #endregion

        #region PCPNDT Form
        public JsonResult SaveApplicantDetails(ApplicantModel model)
        {
            NotificationModel notification = new NotificationModel();

            if (ModelState.IsValid)
            {
                int _applicationId = Session["ApplicationId"] == null ? 0 : Session.GetDataFromSession<int>("ApplicationId");
                int _transactionId = Session["PCPNDTTransactionId"] == null ? 0 : Session.GetDataFromSession<int>("PCPNDTTransactionId");
                FormStatus formStatus = model.FormStatus;

Areas/User/Views/Dashboard/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_AdminLTELayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Dashboard
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Forms</a></li>
        <li class="active">General Elements</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3><span id="spanDrafts"></span></h3>
                    <p>Drafts</p>
                </div>
                <div class="icon">
                    <i class="ion ion-bag"></i>
                </div>
                @Html.ActionLink("More info", "Drafts", "Dashboard", new { Area = "User" }, new { @class = "small-box-footer" })
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h3><span id="spanSubmitted"></span></h3>
                    <p>Submitted Applications</p>
                </div>
                <div class="icon">
                    <i class="ion ion-stats-bars"></i>
                </div>
                @Html.ActionLink("More info", "Submitted", "Dashboard", new { Area = "User" }, new { @class = "small-box-footer" })
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-green">
                <div class="inner">
                    <h3><span id="spanLicenses"></span></h3>
                    <p>Licenses</p>
                </div>
                <div class="icon">
                    <i class="ion ion-person-add"></i>
                </div>
                @Html.ActionLink("More info", "Licenses", "Dashboard", new { Area = "User" }, new { @class = "small-box-footer" })
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-red">
                <div class="inner">
                    <h3><span id="spanQueries"></span></h3>
                    <p>Raised Queries</p>
                </div>
                <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                </div>
                @Html.ActionLink("More info", "Queries", "License", new { Area = "User" }, new { @class = "small-box-footer" })
            </div>
        </div>
        <!-- ./col -->
    </div>
</section>

<script>
    $(function () {
        var url = '@Url.Action("GetUserDashboard", "Dashboard", new { Area = "User" })';
        var jqxhr = $.getJSON(url, function () { })
       .done(function (response) {
           var json;
           if (response instanceof Object)
               json = response;
           else
               json = $.parseJSON(response);
           $('#spanDrafts').text(json.Table[0]["Drafts"]);
           $('#spanSubmitted').text(json.Table1[0]["Submitted"]);
           $('#spanLicenses').text(json.Table2[0]["Licenses"]);
           $('#spanQueries').text(json.Table3[0]["QueriesRaised"]);
       })
   .fail(function (jqxhr, status, error) {
       var err = status + ", " + error;
       console.log("GetUserDashboard Request Failed: " + err);
   });
    });
</script>

Areas/User/Views/Dashboard/Drafts.cshtml
@{
    ViewBag.Title = "Drafts";
    Layout = "~/Views/Shared/_AdminLTELayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Applications
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Forms</a></li>
        <li class="active">General Elements</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Draft</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="tblDraftApplications" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Sl.No</th>
                                <th>Application Number</th>
                                <th>Created On</th>
                                <th>Last Modified On</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
    </section>

<script>
    $(function () {
        $("#tblDraftApplications").DataTable();
        GetDraftApplications();
    });

    function GetDraftApplications() {
        var url = '@Url.Action("GetDraftApplications", "Dashboard", new { Area = "User" })';
        var jqxhr = $.post(url, function () { })
            .done(function (response) {
                var json;
                if (response instanceof Object)
                    json = response;
                else
                    json = $.parseJSON(response);
                BindDetails(json);
            })
            .fail(function (jqxhr, status, error) {
                var err = status + ", " + error;
                console.log("GetDraftApplications in User, Request Failed: " + err);
            });
    }

    function BindDetails(json) {
        var table = $('#tblDraftApplications').DataTable();

        // Clear all existing rows
        table.clear().draw();

        // Bind new rows
        for (var i = 0; i < json.length; i++) {

            table.row.add([
        (i + 1),
        json[i].ApplicationNumber,
        json[i].CreatedOn,
        json[i].LastModifiedOn,
        '<input type="button" value="View" onclick="ViewApplication(' + json[i].Id + ')" />',
        '<input type="button" value="Edit" onclick="EditApplication(' + json[i].Id + ')" />'
            ]);
        }

        table.draw();
    }

    function ViewApplication(id) {
        var viewlink = '@Url.Action("ApplicationView", "License", new { Area = "User", id = 1 })';
        viewlink = viewlink.replace("1", id);
        window.location.href = viewlink;
    }

    function EditApplication(id) {
        var viewlink = '@Url.Action("Edit", "License", new { Area = "User", id = 1 })';
        viewlink = viewlink.replace("1", id);
        window.location.href = viewlink;
    }
</script>

Areas/User/Views/Dashboard/Licenses.cshtml
@{
    ViewBag.Title = "Licenses";
    Layout = "~/Views/Shared/_AdminLTELayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Licenses
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Forms</a></li>
        <li class="active">General Elements</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Licenses</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="tblLicenses" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Sl.No</th>
                                <th>License Number</th>
                                <th>Issued Date</th>
                                <th>Expiry Date</th>
                                <th>District</th>
                                <th>Mandal</th>
                                <th>Village</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
</section>

<script>
    $(function () {
        $("#tblDraftApplications").DataTable();
        GetLicenses();
    });

    function GetLicenses() {
        var url = '@Url.Action("GetLicenses", "Dashboard", new { Area = "User" })';
        var jqxhr = $.post(url, function () { })
            .done(function (response) {
                var json;
                if (response instanceof Object)
                    json = response;
                else
                    json = $.parseJSON(response);
                console.log(json);
                BindDetails(json);
            })
            .fail(function (jqxhr, status, error) {
                var err = status + ", " + error;
                console.log("GetLicenses in User, Request Failed: " + err);
            });
    }

    function BindDetails(json) {
        var table = $('#tblLicenses').DataTable();

        // Clear all existing rows
        table.clear().draw();

        // Bind new rows
        for (var i = 0; i < json.length; i++) {

            table.row.add([
        (i + 1),
        json[i].LicenseNumber,
        json[i].LicenseIssuedDate,
        json[i].LicenseExpiryDate,
        json[i].District,
        json[i].Mandal,
        json[i].Village,
        '<input type="button" value="View" onclick="ViewLicense(' + json[i].Id + ')"/>',
        '<input type="button" value="Ammendments" onclick="Ammendments(' + json[i].Id + ','+ json[i].ServiceId +')"/>',
            ]);
        }

        table.draw();
    }

    function ViewLicense(id) {
        var url = '@Url.Action("GetPCPNDTLicense", "License", new { Area = "User" })';
        var data = {
            transactionId: id
        };
        var jqxhr = $.post(url, data, function () { }, "html")
        .done(function (response) {
            var notificationModel = GetModalJSON();
            notificationModel.Title = "PCPNDT Registration Certificate";
            notificationModel.BodyContent = response;
            notificationModel.IsLargeModal = true;
            ShowModal(notificationModel);
        })
        .fail(function (jqxhr, status, error) {
            var err = status + ", " + error;
            console.log("GetPCPNDTLicense Request Failed: " + err);
        });
    }

    function Ammendments(id, serviceId) {
        console.log(id);
        console.log(serviceId);

        var link = '@Url.Action("Questionnaire", "Amendment", new { Area = "User", id = 1, serviceId = 2 })';
        link = link.replace("1", id);
        link = link.replace("2", serviceId);
        window.location.href = link;
    }
</script>

Areas/User/Views/Dashboard/Submitted.cshtml
@{
    ViewBag.Title = "Submitted";
    Layout = "~/Views/Shared/_AdminLTELayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Applications
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Forms</a></li>
        <li class="active">General Elements</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Sumbitted</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="tblSubmittedApplications" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Sl.No</th>
                                <th>Application Number</th>
                                <th>Created On</th>
                                <th>Submitted On</th>
                                <th>Ack</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
</section>

<script>
    $(function () {
        $("#tblSubmittedApplications").DataTable();
        GetSubmittedApplications();
    });

    function GetSubmittedApplications() {
        var url = '@Url.Action("GetSubmittedApplications", "Dashboard", new { Area = "User" })';
        var jqxhr = $.post(url, function () { })
            .done(function (response) {
                var json;
                if (response instanceof Object)
                    json = response;
                else
                    json = $.parseJSON(response);
                BindDetails(json);
            })
            .fail(function (jqxhr, status, error) {
                var err = status + ", " + error;
                console.log("GetSubmittedApplications in User, Request Failed: " + err);
            });
    }

    function BindDetails(json) {
        var table = $('#tblSubmittedApplications').DataTable();

        // Clear all existing rows
        table.clear().draw();

        // Bind new rows
        for (var i = 0; i < json.length; i++) {

            debugger;
            var ACKLink;
            if (json[i].HasACK != undefined && json[i].HasACK)
                ACKLink = '<input type="button" value="Print" onclick="GetPCPNDTAck(' + json[i].Id + ')" />';
            else
                ACKLink = 'Need approval';


            table.row.add([
        (i + 1),
        json[i].ApplicationNumber,
        json[i].CreatedOn,
        json[i].LastModifiedOn,
        ACKLink,
        '<input type="button" value="View" onclick="ViewApplication(' + json[i].Id + ')" />'
            ]);
        }

        table.draw();
    }

    function ViewApplication(id) {
        var viewlink = '@Url.Action("ApplicationView", "License", new { Area = "User", id = 1 })';
        viewlink = viewlink.replace("1", id);
        window.location.href = viewlink;
    }

    function GetPCPNDTAck(id) {
        var url = '@Url.Action("GetAcknowledge", "Application", new { Area = "User" })';
        var data = {
            applicationId: id
        };
        var jqxhr = $.post(url, data, function () { }, "html")
        .done(function (response) {
            var notificationModel = GetModalJSON();
            notificationModel.Title = "Acknowledgment Certificate";
            notificationModel.BodyContent = response;
            notificationModel.IsLargeModal = true;
            notificationModel.ShowNonActionButton = true;
            notificationModel.NonActionButtonText = 'Close';
            ShowModal(notificationModel);
        })
        .fail(function (jqxhr, status, error) {
            var err = status + ", " + error;
            console.log("GetAcknowledge Request Failed: " + err);
        });
    }
   

   

</script>